### ISSUE TITLE
Title: Dictionary App with Narration

### ISSUE THREAD

**Issue by Atharv-110** [RahulSoni0/Visualizers#4]
## What?
This will be an dictionary app which will fetch the words and the meanings via API and displays it to the user.

## Why?
This app could be useful for everyone as we do not have this much time to go for the physical book i.e. dictionary. This could be easy to use tool as well as very interactive with the user.

## How?
1. HTML, CSS and JS is used for the user interaction.
2. Word meaning API have been used which will fetch all the necessary information about a word.
3. Narration feature will be there like the word and it's meaning will be narrated to the user.

## Demo:
![Screenshot_20221004-195443_Chrome.jpg](https://user-images.githubusercontent.com/87393095/194689391-d9baa011-9daf-4588-a40a-db4729c99a60.jpg)

#### Please assign and consider this issue to me under Hacktoberfest 2022 and add its tags too.

**Comment by RahulSoni0** [comment]
@Atharv-110 looks go to me , move forward and make a pr and dont forget to mention this issue in your pr by adding #your issue no. Here

**Comment by Atharv-110** [comment]
Pull Request number #5 resolves this issue.
