### ISSUE TITLE
Title: Captcha Code Generator (with Verification)

### ISSUE THREAD

**Issue by Atharv-110** [RahulSoni0/Visualizers#8]
## What?
This will be a web app that will generate a captcha code for the security and verification process.

## Why?
The reason behind this script is that many times we need verification to be secured from bots and hackers so we implement this feature to know whether the person accessing our website is genuine or not.

## How?
1. HTML, CSS, and JS are used for user interaction.
2. Script is added in JS to check whether the Captcha code is rewritten correctly or not.

## Demo:
![image](https://user-images.githubusercontent.com/87393095/194698034-9509f1a3-96cb-4896-8e27-015fa1c921cf.png)

#### Please assign and consider this issue to me under Hacktoberfest 2022 and add its tags too.

**Comment by RahulSoni0** [comment]
okay good to go!

**Comment by Atharv-110** [comment]
PR have been raised with #9 number/

**Comment by RahulSoni0** [comment]
Done
